version: '3'
services:
  streamlit-app:
    container_name: "wms-customer-segmentation-container"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    volumes:
      - .:/wms-customer-segmentation
